### ISSUE TITLE
Running error with multi GPU after VM scaling

### ISSUE THREAD

**Issue by rmarquis** [ALIRE-HES-SO/llm-sft-workshop#32]
After scaling the VM, I get an error when running the `distributed_type: MULTI_GPU` config. Curious if that is reproducible.

>[rank0]: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
[rank0]: Last error:
[rank0]: Duplicate GPU detected : rank 0 and rank 2 both on CUDA device 1090

$ uv run accelerate launch   --config_file configs/accelerate_multi.yaml  main.py   --config configs/gretelai/synthetic_text_to_sql/sft.yaml

Complete log:

```
Uninstalled 1 package in 2ms
Installed 1 package in 9ms
Skipping import of cpp extensions due to incompatible torch version 2.8.0+cu128 for torchao version 0.14.1             Please see https://github.com/pytorch/ao/issues/2919 for more info
Skipping import of cpp extensions due to incompatible torch version 2.8.0+cu128 for torchao version 0.14.1             Please see https://github.com/pytorch/ao/issues/2919 for more info
Skipping import of cpp extensions due to incompatible torch version 2.8.0+cu128 for torchao version 0.14.1             Please see https://github.com/pytorch/ao/issues/2919 for more info
Skipping import of cpp extensions due to incompatible torch version 2.8.0+cu128 for torchao version 0.14.1             Please see https://github.com/pytorch/ao/issues/2919 for more info
INFO 03-17 16:14:49 [__init__.py:216] Automatically detected platform cuda.
INFO 03-17 16:14:49 [__init__.py:216] Automatically detected platform cuda.
INFO 03-17 16:14:49 [__init__.py:216] Automatically detected platform cuda.
INFO 03-17 16:14:49 [__init__.py:216] Automatically detected platform cuda.
2026-03-17 16:14:50,277 - __main__ - INFO - loading AutoProcessor
2026-03-17 16:14:50,278 - __main__ - INFO - loading AutoProcessor
2026-03-17 16:14:50,279 - __main__ - INFO - loading AutoProcessor
2026-03-17 16:14:50,286 - __main__ - INFO - loading AutoProcessor
2026-03-17 16:14:53,151 - __main__ - INFO - loading dataset: gretelai/synthetic_text_to_sql
2026-03-17 16:14:53,161 - __main__ - INFO - loading dataset: gretelai/synthetic_text_to_sql
2026-03-17 16:14:53,323 - __main__ - INFO - loading dataset: gretelai/synthetic_text_to_sql
2026-03-17 16:14:53,347 - __main__ - INFO - loading dataset: gretelai/synthetic_text_to_sql
2026-03-17 16:14:55,274 - __main__ - INFO - splitting dataset into train (provided), validation (missing), and test (provided) sets
2026-03-17 16:14:55,274 - __main__ - INFO - splitting dataset into train (provided), validation (missing), and test (provided) sets
2026-03-17 16:14:55,274 - __main__ - INFO - splitting dataset into train (provided), validation (missing), and test (provided) sets
2026-03-17 16:14:55,274 - __main__ - INFO - splitting dataset into train (provided), validation (missing), and test (provided) sets
2026-03-17 16:14:55,287 - __main__ - INFO - loading jinja2 templates from: ./prompts/gretelai/synthetic_text_to_sql
2026-03-17 16:14:55,287 - __main__ - INFO - loading jinja2 templates from: ./prompts/gretelai/synthetic_text_to_sql
2026-03-17 16:14:55,287 - __main__ - INFO - loading jinja2 templates from: ./prompts/gretelai/synthetic_text_to_sql
2026-03-17 16:14:55,287 - __main__ - INFO - loading jinja2 templates from: ./prompts/gretelai/synthetic_text_to_sql
2026-03-17 16:14:55,289 - __main__ - INFO - applying dataset format mapping: conversational_prompt_completion
2026-03-17 16:14:55,289 - __main__ - INFO - applying dataset format mapping: conversational_prompt_completion
2026-03-17 16:14:55,289 - __main__ - INFO - applying dataset format mapping: conversational_prompt_completion
2026-03-17 16:14:55,289 - __main__ - INFO - applying dataset format mapping: conversational_prompt_completion
2026-03-17 16:14:55,583 - __main__ - INFO - loading AutoModel: google/gemma-3-270m-it
2026-03-17 16:14:55,583 - __main__ - INFO - loading AutoModel: google/gemma-3-270m-it
2026-03-17 16:14:55,583 - __main__ - INFO - loading AutoModel: google/gemma-3-270m-it
2026-03-17 16:14:55,583 - __main__ - INFO - loading AutoModel: google/gemma-3-270m-it
2026-03-17 16:14:56,212 - __main__ - INFO - initializing SFT trainer
2026-03-17 16:14:56,212 - __main__ - INFO - initializing SFT trainer
/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:4807: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user.
  warnings.warn(  # warn only once
/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:4807: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user.
  warnings.warn(  # warn only once
2026-03-17 16:14:56,215 - __main__ - INFO - initializing SFT trainer
[rank1]:[W317 16:14:56.711368110 ProcessGroupNCCL.cpp:5023] [PG ID 0 PG GUID 0 Rank 1]  using GPU 1 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can specify device_id in init_process_group() to force use of a particular device.
[rank2]:[W317 16:14:56.711419220 ProcessGroupNCCL.cpp:5023] [PG ID 0 PG GUID 0 Rank 2]  using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can specify device_id in init_process_group() to force use of a particular device.
2026-03-17 16:14:56,217 - __main__ - INFO - initializing SFT trainer
/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:4807: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user.
  warnings.warn(  # warn only once
[rank3]:[W317 16:14:56.712753440 ProcessGroupNCCL.cpp:5023] [PG ID 0 PG GUID 0 Rank 3]  using GPU 1 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can specify device_id in init_process_group() to force use of a particular device.
/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py:4807: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user.
  warnings.warn(  # warn only once
[rank0]:[W317 16:14:57.550039795 ProcessGroupNCCL.cpp:5023] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 as device used by this process is currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect. You can specify device_id in init_process_group() to force use of a particular device.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 416, in <module>
[rank3]:     main()
[rank3]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 162, in main
[rank3]:     trainer = SFTTrainer(
[rank3]:               ^^^^^^^^^^^
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 805, in __init__
[rank3]:     train_dataset = self._prepare_dataset(
[rank3]:                     ^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 894, in _prepare_dataset
[rank3]:     with PartialState().main_process_first():
[rank3]:   File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
[rank3]:     return next(self.gen)
[rank3]:            ^^^^^^^^^^^^^^
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 526, in main_process_first
[rank3]:     yield from self._goes_first(self.is_main_process)
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 409, in _goes_first
[rank3]:     self.wait_for_everyone()
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 403, in wait_for_everyone
[rank3]:     torch.distributed.barrier()
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank3]:     return func(*args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4811, in barrier
[rank3]:     work = group.barrier(opts=opts)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.27.3
[rank3]: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
[rank3]: Last error:
[rank3]: Duplicate GPU detected : rank 3 and rank 1 both on CUDA device 10a0
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 416, in <module>
[rank2]:     main()
[rank2]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 162, in main
[rank2]:     trainer = SFTTrainer(
[rank2]:               ^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 805, in __init__
[rank2]:     train_dataset = self._prepare_dataset(
[rank2]:                     ^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 894, in _prepare_dataset
[rank2]:     with PartialState().main_process_first():
[rank2]:   File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
[rank2]:     return next(self.gen)
[rank2]:            ^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 526, in main_process_first
[rank2]:     yield from self._goes_first(self.is_main_process)
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 409, in _goes_first
[rank2]:     self.wait_for_everyone()
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 403, in wait_for_everyone
[rank2]:     torch.distributed.barrier()
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank2]:     return func(*args, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4811, in barrier
[rank2]:     work = group.barrier(opts=opts)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.27.3
[rank2]: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
[rank2]: Last error:
[rank2]: Duplicate GPU detected : rank 2 and rank 0 both on CUDA device 1090
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 416, in <module>
[rank1]:     main()
[rank1]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 162, in main
[rank1]:     trainer = SFTTrainer(
[rank1]:               ^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 805, in __init__
[rank1]:     train_dataset = self._prepare_dataset(
[rank1]:                     ^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 894, in _prepare_dataset
[rank1]:     with PartialState().main_process_first():
[rank1]:   File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
[rank1]:     return next(self.gen)
[rank1]:            ^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 526, in main_process_first
[rank1]:     yield from self._goes_first(self.is_main_process)
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 409, in _goes_first
[rank1]:     self.wait_for_everyone()
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 403, in wait_for_everyone
[rank1]:     torch.distributed.barrier()
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4811, in barrier
[rank1]:     work = group.barrier(opts=opts)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.27.3
[rank1]: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
[rank1]: Last error:
[rank1]: Duplicate GPU detected : rank 1 and rank 3 both on CUDA device 10a0
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 416, in <module>
[rank0]:     main()
[rank0]:   File "/home/ubuntu/llm-sft-workshop/main.py", line 162, in main
[rank0]:     trainer = SFTTrainer(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 805, in __init__
[rank0]:     train_dataset = self._prepare_dataset(
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/trl/trainer/sft_trainer.py", line 894, in _prepare_dataset
[rank0]:     with PartialState().main_process_first():
[rank0]:   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
[rank0]:     next(self.gen)
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 526, in main_process_first
[rank0]:     yield from self._goes_first(self.is_main_process)
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 414, in _goes_first
[rank0]:     self.wait_for_everyone()
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/state.py", line 403, in wait_for_everyone
[rank0]:     torch.distributed.barrier()
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4811, in barrier
[rank0]:     work = group.barrier(opts=opts)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.distributed.DistBackendError: NCCL error in: /pytorch/torch/csrc/distributed/c10d/NCCLUtils.cpp:77, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.27.3
[rank0]: ncclInvalidUsage: This usually reflects invalid usage of NCCL library.
[rank0]: Last error:
[rank0]: Duplicate GPU detected : rank 0 and rank 2 both on CUDA device 1090
[rank2]:[W317 16:14:59.135638590 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank0]:[W317 16:15:00.572325378 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0317 16:15:00.746000 1737 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1789 closing signal SIGTERM
W0317 16:15:00.747000 1737 torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1790 closing signal SIGTERM
E0317 16:15:00.975000 1737 torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 2 (pid: 1791) of binary: /home/ubuntu/llm-sft-workshop/.venv/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/llm-sft-workshop/.venv/bin/accelerate", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1226, in launch_command
    multi_gpu_launcher(args)
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 853, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 143, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/llm-sft-workshop/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 277, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2026-03-17_16:15:00
  host      : remy-instance-small
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1792)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2026-03-17_16:15:00
  host      : remy-instance-small
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1791)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by rmarquis** [comment]
I confirm this works. There is already a warning about it, demanding to set the value to '2' when using the Medium instance.
